# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pr: none  # Disable PR triggers, can be adjusted as needed
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: AzureCLI@2
  displayName: 'Update Kubernetes cluster'
  inputs:
    azureSubscription: 'sp-devops'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Variables
      RESOURCE_GROUP="RG-PFE"
      VM_NAME="Elasticsearch-Ala"

      COMMAND='
      cd /home/admala
      curl -L -o elk.zip https://github.com/alazarrouk-cafpi/elk/archive/refs/heads/main.zip
      unzip elk.zip
      sudo chmod 777 elk-main/pipelines-scripts/update-elk.sh  
      sudo bash ./elk-main/pipelines-scripts/update-elk.sh
      '
      # Execute the command on the VM
      az vm run-command invoke \
        --command-id RunShellScript \
        --name $VM_NAME \
        --resource-group $RESOURCE_GROUP \
        --scripts "$COMMAND"
  
  env:
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_SECRET: $(AZURE_SECRET)
    AZURE_TENANT: $(AZURE_TENANT)
