# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pr: none  # Disable PR triggers, can be adjusted as needed
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: AzureCLI@2
  displayName: 'Update Kubernetes cluster'
  inputs:
    azureSubscription: 'sp-devops'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Variables
      RESOURCE_GROUP="RG-PFE"
      VM_NAME="Elasticsearch-Ala"

      COMMAND='
      cd /home/admala
      rm -rf elk*
      curl -L -o elk.zip https://github.com/alazarrouk-cafpi/elk/archive/refs/heads/main.zip
      unzip elk.zip
      rm -rf /home/admala/mnt/data/elastalert-config/config/*
      rm -rf /home/admala/mnt/data/elastalert-config/rules/*
      rm -rf /home/admala/mnt/data/elastalert-config/custom_modules/*
      cp -r  /home/admala/elk-main/elastalert/config/* /mnt/data/elastalert-config/config/
      cp -r  /home/admala/elk-main/elastalert/rules/* /mnt/data/elastalert-config/rules/
      cp -r  /home/admala/elk-main/elastalert/custom_modules/* /mnt/data/elastalert-config/custom_modules/
      cat <<EOF > /etc/exports
      /mnt/data/certs 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      /mnt/data/fleet-data 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      /mnt/data/logstash-data 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      /mnt/data/kibana-data 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      /mnt/data/es-data 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      /mnt/data/elastalert-data 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      /mnt/data/elastalert-config/config 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      /mnt/data/elastalert-config/rules 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      /mnt/data/elastalert-config/custom_modules 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      /mnt/data/filebeatlogs-data 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      /mnt/data/filebeatmetrics-data 10.53.2.0/24(rw,sync,no_root_squash,no_subtree_check)
      EOF
      exportfs -a
      systemctl restart nfs-kernel-server
      microk8s kubectl apply -f /home/admala/elk-main/kubernetes/configMaps/
      microk8s kubectl apply -f /home/admala/elk-main/kubernetes/persistent-volumes/
      microk8s kubectl apply -f /home/admala/elk-main/kubernetes/persistent-volumes-claims/
      microk8s kubectl delete deployment elastalert 
      microk8s kubectl delete deployment es01
      microk8s kubectl delete deployment filebeat-logs
      microk8s kubectl delete deployment filebeat-metrics
      microk8s kubectl delete deployment fleet
      microk8s kubectl delete deployment kibana
      microk8s kubectl delete deployment logstash
      microk8s kubectl apply -f /home/admala/elk-main/kubernetes/elk-deployments/elasticsearch-deployment.yaml
      microk8s kubectl apply -f /home/admala/elk-main/kubernetes/elk-deployments/logstash-deployment.yaml
      microk8s kubectl apply -f /home/admala/elk-main/kubernetes/elk-deployments/kibana-deployment.yaml
      microk8s kubectl apply -f /home/admala/elk-main/kubernetes/elk-deployments/fleet-deployment.yaml
      microk8s kubectl apply -f /home/admala/elk-main/kubernetes/elk-deployments/filebeat-logs-deployment.yaml
      microk8s kubectl apply -f /home/admala/elk-main/kubernetes/elk-deployments/filebeat-metrics-deployment.yaml
      microk8s kubectl apply -f /home/admala/elk-main/kubernetes/elk-deployments/elastalert2-deployment.yaml
      '
      # Execute the command on the VM
      az vm run-command invoke \
        --command-id RunShellScript \
        --name $VM_NAME \
        --resource-group $RESOURCE_GROUP \
        --scripts "$COMMAND"
  
  env:
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_SECRET: $(AZURE_SECRET)
    AZURE_TENANT: $(AZURE_TENANT)
