# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pr: none  # Disable PR triggers, can be adjusted as needed
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
    # Install Ansible
    pip3 install "ansible==2.9.17"
  displayName: 'Install Ansible'
  
- script: |
    # Install Ansible rm module
    pip3 install ansible[azure]
  displayName: 'Install Ansible rm module'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-pipeline-sp'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Login to Azure using service principal
      az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_SECRET --tenant $AZURE_TENANT
      # Variables
      RESOURCE_GROUP="rg-net-prod-01"
      VM_NAME="masterk8s"
      VAULT_PASSWORD_FILE="/home/admala/vault-password.txt"
      COMMAND='
      cd /home/admala
      ansible-playbook  --vault-password-file $VAULT_PASSWORD_FILE  -i elk-main/ansible/hosts.ini  elk-main/ansible/kubernetes-playbook.yaml -vvv
      '

      # Execute the command on the VM
      az vm run-command invoke \
        --command-id RunShellScript \
        --name $VM_NAME \
        --resource-group $RESOURCE_GROUP \
        --scripts "$COMMAND"
  displayName: 'Run Command on Azure VM'
  env:
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_SECRET: $(AZURE_SECRET)
    AZURE_TENANT: $(AZURE_TENANT)
