pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Run Commands on Azure VM'
  inputs:
    azureSubscription: 'sp-devops'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Variables
      RESOURCE_GROUP="RG-PFE"
      VM_NAME="Elasticsearch-Ala"
      
      # Define the script to run on VM
      SCRIPT='#!/bin/bash
      echo "Starting script execution"
      cd /home/admala
      sudo bash update-elk.sh
      exit 0'

      # Execute the script on the VM
      az vm run-command invoke \
        --resource-group $RESOURCE_GROUP \
        --name $VM_NAME \
        --command-id RunShellScript \
        --scripts "$SCRIPT"
        
      echo "All commands executed successfully."
