apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 100M
  volumeName: certs-pv