apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastalert2-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi
  volumeName: elastalert2-pv