apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastalert-modules-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 50Mi
  volumeName: elastalert-modules-pv