apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esdata-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 80Gi
  volumeName: esdata-pv