apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastalert-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 500Mi
  volumeName: elastalert-pv