apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebeat-logs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi
  volumeName: filebeat-logs-pv