apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstashdata-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 10Gi
  volumeName: logstashdata-pv