# logstash.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastalert
  template:
    metadata:
      labels:
        app: elastalert
    spec:
     
      initContainers:
        - name: uploading-rules
          image: busybox
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              mkdir -p /opt/elastalert/custom_modules
              mkdir -p /opt/elastalert/config
              mkdir -p /opt/elastalert/certs
              ls /opt/elastalert
              wget https://github.com/moparisthebest/static-curl/releases/download/v7.85.0/curl-amd64
              mv curl-amd64 /bin/curl
              chmod +x /bin/curl
              while ! curl -s http://logstash:9600/_node/stats/pipelines | jq '.pipelines.logs.events.duration_in_millis > 0'; do
                  echo "Waiting for Logstash pipeline 'logs' to be ready..."
                  sleep 5
              done
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: elk-config
                  key: ELASTIC_PASSWORD
         
      containers:
        - name: elastalert
          image: jertel/elastalert2:latest
          ports:
            - containerPort: 3030
          resources:
            requests:
              memory: 300Mi
              cpu: 300m
            limits:
              memory: 400Mi
              cpu: 400m
          command: ["/bin/sh"]
          args:
            - -c
            - |
              elastalert-create-index --config /opt/elastalert/config/config.yaml
              elastalert --config /opt/elastalert/config/config.yaml --verbose
          volumeMounts:
            - mountPath: /opt/elastalert/certs
              name: certs

            - mountPath: /opt/elastalert/config
              name: elastalert2config

            - mountPath: /opt/elastalert/rules
              name: elastalert2rules

            - mountPath: /opt/elastalert/custom_modules
              name: elastalert2modules

      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs-pvc

        - name: elastalert2data
          persistentVolumeClaim:
            claimName: elastalert-pvc

        - name: elastalert2config
          persistentVolumeClaim:
            claimName: elastalert-config-pvc

        - name: elastalert2rules
          persistentVolumeClaim:
            claimName: elastalert-rules-pvc

        - name: elastalert2modules
          persistentVolumeClaim:
            claimName: elastalert-modules-pvc

        - name: config-folder
          emptyDir: {}

        - name: rules-folder
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: elastalert2
spec:
  ports:
    - port: 3030
      targetPort: 3030
  selector:
    app: elastalert2
