apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-logs
  labels:
    app: filebeat-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat-logs
  template:
    metadata:
      labels:
        app: filebeat-logs
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.14.1
        args: [
          "-c", "/usr/share/filebeat/filebeat.yml",
          "-e"
        ]
        resources:
          limits:
            memory: 200Mi
            cpu: 200m

          requests:
            memory: 100Mi
            cpu: 100m

        volumeMounts:
        - name: filebeatlogsdata
          mountPath: /usr/share/filebeat/data

        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml

      volumes:
      - name: config
        configMap:
          name: filebeat-logs-config
      
      - name: filebeatlogsdata
        persistentVolumeClaim:
          claimName: filebeat-logs-pvc

