apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-logs
  labels:
    app: filebeat-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat-logs
  template:
    metadata:
      labels:
        app: filebeat-logs
    spec:
      initContainers:
        - name: wait-for-logstash
          image: busybox
          command:
            - sh
            - -c
            - |
              wget https://github.com/moparisthebest/static-curl/releases/download/v7.85.0/curl-amd64
              mv curl-amd64 /bin/curl
              chmod +x /bin/curl
              wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
              chmod +x jq
              mv jq /bin/jq
              while ! curl -s http://logstash:9600/_node/pipelines | jq -e '.pipelines.logs.status == "green"' >/dev/null; do
                  echo "Waiting for Logstash pipeline 'logs' to be ready..."
                  sleep 5
              done
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: elk-config
                  key: ELASTIC_PASSWORD
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.14.1
        args: [
          "-c", "/usr/share/filebeat/filebeat.yml",
          "-e"
        ]
        resources:
          limits:
            memory: 200Mi
            cpu: 200m

          requests:
            memory: 100Mi
            cpu: 100m

        volumeMounts:
        - name: filebeatlogsdata
          mountPath: /usr/share/filebeat/data

        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml

      volumes:
      - name: config
        configMap:
          name: filebeat-logs-config
      
      - name: filebeatlogsdata
        persistentVolumeClaim:
          claimName: filebeat-logs-pvc

