apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-metrics-config
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: azure-blob-storage
      id: azurestmonitoringcafpi01
      enabled: true
      account_name: sapfe
      auth.shared_credentials.account_key: JYUQkMiI6C8G6uTbgKfpX0XY4ubTZSl3WSLJ8Omn/fj2LCDiBx1DUMlNCDsnkvw/Hf/PWn7kS0ns+AStF308RA==
      containers:
      - name: insights-metrics-pt1m
        max_workers: 3
        poll: true
        poll_interval: 60s
    filebeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
    setup.template.settings:
      index.number_of_shards: 1
    setup.kibana:
    output.logstash:
      hosts: ["logstash:5045"]
    processors:
      - decode_json_fields:
          document_id: ""
          fields: [""]
          max_depth: 1
          target: ""
      - add_host_metadata:
          when.not.contains.tags: forwarded
      - add_cloud_metadata: ~
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~