apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-logs-config
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: azure-blob-storage
      id: azurestmonitoringcafpi01
      enabled: true
      account_name: sapfe01
      auth.shared_credentials.account_key: mSgBse/6pJBEdGD0/llQSdpf5Vh4HVZiCJ8xawLL5q5N/uMG+AncFT5n6VNI8NbXVVacGUtUqnss+AStcrlhZQ==
      containers:
      - name: insights-logs-appservicehttplogs
        max_workers: 3
        poll: true
        poll_interval: 60s
    filebeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
    setup.template.settings:
      index.number_of_shards: 1
    setup.kibana:
    output.logstash:
      hosts: ["logstash:5044"]
    processors:
      - decode_json_fields:
          document_id: "time"
          fields: ["message"]
          max_depth: 1
          target: ""
      - add_host_metadata:
          when.not.contains.tags: forwarded
      - add_cloud_metadata: ~
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~
  