apiVersion: v1
kind: PersistentVolume
metadata:
  name: certs-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany 
  nfs:
    path: /mnt/data/certs
    server: 10.53.2.115