apiVersion: v1
kind: PersistentVolume
metadata:
  name: esdata-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteMany 
  nfs:
    path: /mnt/data/es-data
    server: 10.53.2.115