apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastalert2-config-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany 
  nfs:
    path: /mnt/data/elastalert-config/config
    server: 10.53.2.115