apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastalert2-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany 
  nfs:
    path: /mnt/data/elastalert-data
    server: 10.53.2.115