apiVersion: v1
kind: PersistentVolume
metadata:
  name: esconfig-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany 
  nfs:
    path: /mnt/data/es-config
    server: 10.53.2.115