apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebeat-metrics-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany 
  nfs:
    path: /mnt/data/filebeatmetrics-sdata
    server: 10.53.2.115