apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleetdata-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany 
  nfs:
    path: /mnt/data/fleet-data
    server: 10.53.2.115