apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibanadata-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data/kibana-data
    server: 10.53.2.115