apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstashdata-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany 
  nfs:
    path: /mnt/data/logstash-data
    server: 10.53.2.115