---
- name: Setup workers virtual machines
  hosts: workers
  become: yes
  vars_files:
    - /home/admala/vault.yml
  tasks:
    - name: Setting up dependencies
      shell: |
        apt-get update -y
        apt install curl net-tools wget unzip openjdk-17-jdk -y
        
    - name: Setting up NFS client
      shell: |
        apt-get install nfs-common -y
        systemctl enable nfs-common
      ignore_errors: yes  
    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: yes
        state: present

    - name: Add user to microk8s group
      user:
        name: admala
        groups: microk8s
        append: yes

    - name: Ensure ~/.kube directory exists
      file:
        path: /home/admala/.kube
        state: directory
        owner: admala
        mode: '0700'

    - name: Wait for MicroK8s to be ready
      command: microk8s status --wait-ready
      become_user: admala
      environment:
        HOME: /home/admala

    - name: Enable DNS in MicroK8s
      command: microk8s enable dns
      become_user: admala
      environment:
        HOME: /home/admala

    - name: Enable storage in MicroK8s
      command: microk8s enable storage
      become_user: admala
      environment:
        HOME: /home/admala

    - name: Install NFS common package
      apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: Load nf_conntrack module
      modprobe:
        name: nf_conntrack

    - name: Set netfilter conntrack max
      sysctl:
        name: net.netfilter.nf_conntrack_max
        value: '131072'
        state: present

    - name: Restart MicroK8s daemon
      systemd:
        name: snap.microk8s.daemon-kubelite
        state: restarted