---
- name: Deploy SSH Keys to Managed Nodes
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ensure the .ssh directory exists
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: '0700'

    - name: Copy the SSH public key to the managed node
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"